title: Samip Paudel 
description: >- 
  Samip's personal site 
lang: en-US 
timezone: America/New_York 
image: assets/img/
repo: https://github.com/smpdl/smpdl.github.io
mode: dark

author:
  name: Samip Paudel 
  bio: >- 

  username: spaudel 
  github: smpdl 
  email: spaudel@vassar.edu 


url: "https://smpdl.github.io/" 
baseurl:
permalink: /:title/
google_analytics: 
fb_appid:


collections:
  posts:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge


defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:


number_of_posts: 5

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
